name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ###############################################################################
  # SETUP                                                                       #
  ###############################################################################
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/auto-cancel-redundant-job@v1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: '14.x'
    - name: Setup Cache
      uses: actions/cache@v2.1.1
      with:
        path: .yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
    - name: Install dependencies
      run: yarn install --immutable
      env:
        YARN_CHECKSUM_BEHAVIOR: update

  ###############################################################################
  # COMMITLINT                                                                  #
  ###############################################################################
  commitlint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Commit Lint
      uses: wagoid/commitlint-github-action@v3.0.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ###############################################################################
  # ESLINT                                                                      #
  ###############################################################################
  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: '13.x'
    - name: Setup Cache
      uses: actions/cache@v2.1.1
      with:
        path: .yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
    - name: Install dependencies
      run: yarn install --immutable --immutable-cache
    - name: ESLint
      run: yarn run eslint

  ###############################################################################
  # RELEASE                                                                     #
  ###############################################################################
  release:
    needs: [eslint, commitlint]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate release token
      id: release_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.RELEASE_APP_ID }}
        private_key: ${{ secrets.RELEASE_PRIVATE_KEY }}
    - name: Get branch
      uses: rlespinasse/github-slug-action@2.1.0
    - name: Release
      uses: ridedott/release-me-action@master
      if: ${{ env.GITHUB_REF_SLUG == 'master' }}
      with:
        node-module: true
      env:
        GITHUB_TOKEN: ${{ steps.release_token.outputs.token }}

