name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ###############################################################################
  # SETUP                                                                       #
  ###############################################################################
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: .yarn
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_CHECKSUM_BEHAVIOR: update
          YARN_NPM_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}

  ###############################################################################
  # COMMITLINT                                                                  #
  ###############################################################################
  commitlint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ###############################################################################
  # ESLINT                                                                      #
  ###############################################################################
  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: .yarn
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_CHECKSUM_BEHAVIOR: update
      - name: ESLint
        run: yarn run eslint

  ###############################################################################
  # RELEASE                                                                     #
  ###############################################################################
  release:
    needs: [eslint, commitlint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate release token
        id: release_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RELEASE_APP_ID }}
          private_key: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Get branch
        uses: rlespinasse/github-slug-action@1.1.0
      - name: Release
        uses: ridedott/release-me-action@v3.1.12
        if: ${{ env.GITHUB_REF_SLUG == 'master' }}
        with:
          node-module: true
        env:
          GITHUB_TOKEN: ${{ steps.release_token.outputs.token }}
